version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 8
    labels:
      - "dependencies"
      - "javascript"
      - "dependabot"
    groups:
      development-patch-minor:
        dependency-type: "development"
        update-types:
          - "patch"
          - "minor"
        exclude-patterns:
          - "pdfjs-dist"
