packages:
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  nx: true
  unrs-resolver: true
  vue-demi: true
overrides:
  '@mlightcad/data-model': '^1.10.3'
  '@mlightcad/dxf-json-converter': '^1.10.3'
  '@mlightcad/libredwg-converter': '^3.10.3'
  '@mlightcad/mtext-input-box': '^0.2.20'
  '@mlightcad/mtext-renderer': '^0.11.9'
  '@mlightcad/ribbon': '^0.1.10'
  '@babel/plugin-transform-modules-systemjs': '7.29.4'
  axios: '1.16.0'
  brace-expansion: '5.0.6'
  dompurify: '3.4.11'
  element-plus: '^2.12.0'
  fast-uri: '3.1.2'
  form-data: '4.0.6'
  glob: '^13.0.6'
  linkify-it: '5.0.1'
  lodash: '4.18.1'
  lodash-es: '4.18.1'
  'js-yaml@3': '3.15.0'
  'js-yaml@4': '4.2.0'
  markdown-it: '14.2.0'
  minimatch: '9.0.7'
  postcss: '8.5.10'
  tmp: '0.2.7'
  three: '^0.172.0'
  vue: '^3.4.21'
  vue-i18n: '^11.4.4'
